[package]
name = "desktop"
version = "0.1.0"
edition = "2021"

[dependencies]
chip8_core = { path = "../chip8_core" }
sdl2 = { version = "0.35", features = ["bundled"] } # Check for the latest version at https://crates.io/crates/sdl2
